DROP TABLE IF EXISTS users, items, bookings, comments, requests;

CREATE TABLE IF NOT EXISTS users (
                                     id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name VARCHAR(255) NOT NULL,
                                     email VARCHAR(512) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS requests (
                                        request_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        description  VARCHAR(1000) NOT NULL,
                                        requester_id BIGINT REFERENCES users (id) ON DELETE CASCADE,
                                        created_date TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS items (
                                     id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name VARCHAR(255) NOT NULL,
                                     description VARCHAR(255) NOT NULL,
                                     available BOOLEAN NOT NULL,
                                     owner BIGINT REFERENCES users (id),
                                     request_id BIGINT REFERENCES requests (request_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS bookings (
                                        id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        start TIMESTAMP,
                                        end_time TIMESTAMP,
                                        status VARCHAR(255),
                                        item_id BIGINT REFERENCES items(id),
                                        booker BIGINT REFERENCES users(id)
);


CREATE TABLE IF NOT EXISTS comments (
                                        id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        text VARCHAR(500),
                                        item_id BIGINT REFERENCES items(id),
                                        user_id BIGINT REFERENCES users(id),
                                        created TIMESTAMP
);


